### PR TITLE
Add @otherguy/elysia-logging

### PR DESCRIPTION
**Pull request by otherguy**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/elysiajs/awesome-elysia/blob/main/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Review by gaurishhs — CHANGES_REQUESTED** [review]
Please add a full stop. Don't make it end on a bracket

**Comment by gaurishhs** [comment]
`Logging middleware for a variety of loggers (Pino, Winston, etc.)` would probably be better

**Comment by otherguy** [comment]
@gaurishhs agreed!

**Comment by gaurishhs** [comment]
Thanks!

**Pull request merged**
